version: 2.0 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    steps: 
      - 
        checkout: ~
      - 
        run: 
          command: "gradle test"
          name: "gradle test"
      - 
        store_test_results: 
          path: /build/test-results
    test: 
      docker: 
        - 
          image: "circleci/openjdk:8-jdk"
      steps: 
        - 
          checkout: ~
        - 
          run: 
            command: "gradle jar"
            name: "gradle jar"
        - 
          store_artifacts: 
            destination: prefix
            path: /code/test-results
workflows: 
  jobs: 
    - build
    - test

