version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
          name: gradle test
          command: gradle test
      - store_test_results:
          path: /build/test-results
   test:
     docker:
       - image: circleci/openjdk:8-jdk
      steps:
      - checkout:
      -run:
          name: gradle jar
          command: gradle jar
      - store_artifacts:
          path: /code/test-results
          destination: prefix
workflows:
   version: 2.0
   feature_master:
      jobs:
         - build:
              filters:
                 branches:
                    only:
                       - feature/*
         - test:
              filters:
                 branches:
                    only: master
